services:
  - type: web
    name: autogalaxy
    env: python
    plan: free
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn neq.wsgi:application"
    pythonVersion: 3.12.3
